//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHAconexionSAP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKPO_DUMM
    {
        public string EBELN { get; set; }
        public decimal EBELP { get; set; }
        public string TXZ0 { get; set; }
        public string MATNR { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> BPUMZ { get; set; }
        public Nullable<decimal> BPUMN { get; set; }
        public Nullable<decimal> NETWR { get; set; }
        public Nullable<decimal> BRTWR { get; set; }
        public Nullable<decimal> H_QUANTITY { get; set; }
        public Nullable<decimal> H_VAL_LOCCUR { get; set; }
        public Nullable<decimal> H_VAL_FORCUR { get; set; }
        public string H_VAL_CURRENCY { get; set; }
        public Nullable<decimal> H_ANT_PAG { get; set; }
        public Nullable<decimal> H_ANT_SOL { get; set; }
        public Nullable<decimal> H_ANT_AMORT { get; set; }
    
        public virtual EKKO_DUMM EKKO_DUMM { get; set; }
    }
}
